### PR TITLE
Sync robustness fixes

### PR DESCRIPTION
**Pull request by SimonWoolf**
Fixes https://github.com/ably/ably-js/issues/300 . Will expand that ticket and do prs for lib version qs and trans pref tomorrow.

### CODE REVIEW

**Comment by paddybyers** [comment]
Re: https://github.com/ably/ably-js/pull/302/commits/9c5295ac91c85e1596e626bc2365143ef82c58f5

in realtime we have an `EventEmitter.timedOnce()` for things like this. It would be nice for it to be a bit more generic.

Otherwise LGTM.

**Comment by mattheworiordan** [comment]
Awesome 👍

**Comment by SimonWoolf** [comment]
> in realtime we have an EventEmitter.timedOnce() for things like this

good idea, but should probably convert all one-off timers at once rather than just this one -- added a refactoring issue https://github.com/ably/ably-js/issues/306

**Comment by SimonWoolf** [comment]
Merged as 8a3ff82

**Pull request closed without merging**
