### PR TITLE
Publish messages serially

### PR DESCRIPTION
**Pull request by mattheworiordan**
Fixes a probable issue when publishing multiple messages over REST concurrently in mobile browsers.

In response to https://github.com/ably/ably-js/issues/164

### CODE REVIEW

**Comment by mattheworiordan** [comment]
@SimonWoolf this makes the tests pass on my mobile browser.

cc @paddybyers

**Comment by SimonWoolf** [comment]
Thanks :)

**Comment by SimonWoolf** [comment]
And ably-js-browsers-min is back to normal! \o/ https://ci.ably.io/job/ably-js-browsers-min/451/

**Comment by SimonWoolf** [comment]
@mattheworiordan actually, quick question -- do you have a sense of what actually went wrong in mobile safari with the old code? It seems a bit worrying that waiting for the publish callback fixes things -- ably-js should be able to handle someone spewing 20 publishes at once without a problem (and does, on every other browser). (Even if they're published out of order, that won't matter for publishvariations since the received messages are all poured into the case statement).

**Comment by mattheworiordan** [comment]
> quick question -- do you have a sense of what actually went wrong in mobile safari with the old code?

No, unfortunately not, I just found it odd that we were publishing that number of messages over REST in a short period of time which means that if a mobile browser was intentionally rate / concurrency limiting things, it could result in timeouts.  Nothing specific unfortunately

**Pull request merged**
