### PR TITLE
clientId specs

### PR DESCRIPTION
**Pull request by mattheworiordan**
This covers off some of the requirements described in the [recent updates to the spec in regards to clientId](https://github.com/ably/docs/commit/e5d66bdeb50994c82b21cae4a1a6aecfac26adbb)

@paddybyers most of these tests don't pass because of the known implicit and explicit `clientId` issues.  Specifically the following is failing:

* implicit clientId not added via REST publish
* invalid clientId not rejected when publishing over Realtime or REST

### CODE REVIEW

**Comment by SimonWoolf** [comment]
Also: @simonwoolf to make ably-js use wildcard clientId when have key but getting token is forced by useTokenAuth and no clientId set (+ test)

**Comment by SimonWoolf** [comment]
Added some more test fixes & code changes (and a couple more tests), the tests now all pass.

Not for merging until we've decided what to do about null/wildcard clientIds -- PR currently includes https://github.com/ably/ably-js/commit/83e91b7ec57d113f03a1d0cc810fb11ac71d3f98 which may have to be removed depending what we decide.

I'll rebase down the commits I made that modified matt's commits before merging, but left them separately for now in case anyone wants to see the changes explicitly.

**Comment by mattheworiordan** [comment]
Mostly looks good, nice work @SimonWoolf

**Comment by SimonWoolf** [comment]
Squashed everything down, removed the wildcard tokenauth commit and associated test, and used connection#key for the init test (and added connection#serial https://github.com/ably/ably-js/commit/dde82f574e5e738900dc7d34873b5a47ccdb90bd)

**Comment by mattheworiordan** [comment]
:+1:

**Pull request merged**
