### PR TITLE
Make presence#history available to both realtime and rest channels

### PR DESCRIPTION
**Pull request by SimonWoolf**
Fixes https://github.com/ably/ably-js/issues/84

### CODE REVIEW

**Comment by paddybyers** [comment]
Would it not work simply to have Realtime Presence extend Rest Presence?

**Comment by mattheworiordan** [comment]
Looks good, :+1:

**Comment by SimonWoolf** [comment]
@paddybyers Utils.inherits seems to break if inheriting from more than one object, but I only want history() so I guess it's not too messy to do that manually, and I it is a bit neater extracted. I pushed that approach up to [presence-history-2](https://github.com/ably/ably-js/compare/presence-history-2?expand=1) branch

**Comment by SimonWoolf** [comment]
Closing in favour of https://github.com/ably/ably-js/pull/87

**Pull request closed without merging**
