### PR TITLE
[WIP] - Fix failing auth_expired_token_string_* tests on IE11

### PR DESCRIPTION
**Pull request by funkyboy**

### CODE REVIEW

**Comment by funkyboy** [comment]
Notice that [in this build](https://travis-ci.org/ably/ably-js/builds/358590329) all the failing `auth_expired_token_string_*` tests fail due to a timeout. E.g.
```
IE 11.0.0 (Windows 8.1.0.0)  auth_expired_token_string_with_web_socket_binary_transport FAILED
	408; {"message":"Request aborted due to request timeout expiring (event type: abort)","code":null,"statusCode":408}
	AssertionError: 408; {"message":"Request aborted due to request timeout expiring (event type: abort)","code":null,"statusCode":408}
	AssertionError: 408; {"message":"Request aborted due to request timeout expiring (event type: abort)","code":null,"statusCode":408}
	   at fail (/home/travis/build/ably/ably-js/node_modules/karma-nodeunit/lib/nodeunit.js:1240:3)
	   at ok (/home/travis/build/ably/ably-js/node_modules/karma-nodeunit/lib/nodeunit.js:1260:17)
	   at Anonymous function (/home/travis/build/ably/ably-js/node_modules/karma-nodeunit/lib/nodeunit.js:1563:17)
	   at Anonymous function (/home/travis/build/ably/ably-js/spec/realtime/auth.test.js:695:5)
	   at Anonymous function (/home/travis/build/ably/ably-js/browser/static/ably.js:8889:6)
	   at callListener (/home/travis/build/ably/ably-js/browser/static/ably.js:4219:4)
	   at Anonymous function (/home/travis/build/ably/ably-js/browser/static/ably.js:4369:4)
	   at Anonymous function (/home/travis/build/ably/ably-js/browser/static/ably.js:4743:4)
	   at EventEmitter.prototype.emit (/home/travis/build/ably/ably-js/browser/static/ably.js:4368:3)
	   at XHRRequest.prototype.complete (/home/travis/build/ably/ably-js/browser/static/ably.js:10970:4)
	Expected 2 assertions, 1 ran
```

Also suspicious that the error has a `"code":null`

**Comment by funkyboy** [comment]
Update: `"code":null` is not suspicious when, as in this case, there's a request that didn't receive a reply from the server before the timeout.
Ref: https://ably-real-time.slack.com/archives/C030C5YLY/p1522139843000388

**Comment by funkyboy** [comment]
Curiously enough, when running only `auth_expired_token_string_*` tests everything works
https://travis-ci.org/ably/ably-js/builds/358817055

Suspicion: when running the whole test suite, `auth_expired_token_string_*` tests (and IE11) are badly influenced by some other tests that are run before.

**Comment by SimonWoolf** [comment]
Per https://github.com/ably/ably-js/pull/495#issuecomment-376302786 , if you just want to run a branch through ci and aren't looking for feedback, please don't make a PR

**Pull request closed without merging**
