### PR TITLE
Publish to new CDN bucket only

### PR DESCRIPTION
**Pull request by surminus**
We've finally migrated to the new bucket, so we can stop publishing to the old bucket, which I intend to delete.

### CODE REVIEW

**Review by owenpearson — CHANGES_REQUESTED** [review]
Looks good, but we should also update the bucket name in `scripts/README.md`

**Comment by surminus** [comment]
Thanks @owenpearson, updated

**Review by owenpearson — APPROVED** [review]
LGTM, thanks

**Comment by surminus** [comment]
@owenpearson, can you merge? I am not authorized to do so :cry:

**Pull request merged**
