### PR TITLE
Fix error creation while unenveloping

### PR DESCRIPTION
**Pull request by funkyboy**
Fixes this failing test https://travis-ci.org/ably/ably-js/jobs/358320054#L2332
caused by this exception https://travis-ci.org/ably/ably-js/jobs/358320054#L2322

### CODE REVIEW

**Comment by SimonWoolf** [comment]
:+1: 
also, looks like `err` in lines 53,54,55 should be `wrappedErr`

**Comment by funkyboy** [comment]
Hey I didn't ask for a review yet :)

**Comment by paddybyers** [comment]
> I didn't ask for a review yet :)

In other repos we're keeping a `[WIP]` in a PR subject line if you want to stop over-eager reviewers

**Comment by funkyboy** [comment]
I was waiting for the results of Travis. Now, pre-alerting you. I am_ about to ask_ for a review.

**Comment by funkyboy** [comment]
Will likely squash the 2 commits after approval. Agree?

**Comment by SimonWoolf** [comment]
> Hey I didn't ask for a review yet :)
> I was waiting for the results of Travis.

If all you want to do is run a branch through ci, there's better ways of doing it than making a PR -- new PRs (and any new commits on them) sends emails to everyone watching the repo, which is unnecessary noise if you're not actually looking for feedback (as well as cluttering up the PRs tab).

I've [configured travis to](https://github.com/ably/ably-js/commit/f0f2d15dcadd75bae4503eb2e71ffbce2b683d29) build any branch whose name ends in `-ci`, so now you can kick off a ci run just by pushing to such a branch without making a PR.

("[WIP]" PRs are still useful if you want to ask for help/feedback while part-way through something)

**Comment by funkyboy** [comment]
Here's what happened:
- was quite sure of the fix
- just wanted to check Travis results before asking for review
- thought it was a matter of minutes

That's why I didn't label it with `[WIP]`. But I should have :)

**Pull request merged**
