### PR TITLE
Add slack/email notifications from Travis

### PR DESCRIPTION
**Pull request by funkyboy**

### CODE REVIEW

**Comment by funkyboy** [comment]
@SimonWoolf if you are receiving emails from Travis, this is ready for review.

**Comment by SimonWoolf** [comment]
> if you are receiving emails from Travis, this is ready for review.

I'm not as this pr hasn't yet added email addresses to .travis.yml, so it's still just going off git committer data -- could you add both of our emails per https://ably-real-time.slack.com/archives/C030APSH3/p1519139591000291

also:
- I had a quick look in #client-library-update to find an example of a notification from this pr, but couldn't see it -- could you link to one to show that it's working
- I don't really care what style we use for yaml, but if you particularly want to make style changes they should be (a) in their own commit, separate from any content changes (in fact preferably their own pr), and (b) applied consistently to the whole file, which this is currently not

**Comment by funkyboy** [comment]
@SimonWoolf 

- Slack example here: https://ably-real-time.slack.com/archives/C0URKD9U2/p1519207873000021
- added email addresses
- Opened issue about Travis .yml https://github.com/ably/ably-js/issues/479

**Comment by funkyboy** [comment]
@SimonWoolf re-ready for review.

**Comment by SimonWoolf** [comment]
@funkyboy I don't have an email from travis for the latest build failing (https://travis-ci.org/ably/ably-js/builds/346731234 ). Do you?

(also, you haven't yet removed the style changes from this pr)

**Comment by funkyboy** [comment]
@SimonWoolf 
- removed style changes from Travis file.

As for the missing email about [build](https://travis-ci.org/ably/ably-js/builds/346731234) failed, the reason is that "Pull Request builds do not trigger email notifications" (from https://docs.travis-ci.com/user/notifications/#Configuring-email-notifications). So I:

- turned off builds on PRs
- turned on build on branches
- removed the "build only master branch" specification

This still shows the Travis widget when a branch is part of a PR.

Ready again for review.

**Comment by SimonWoolf** [comment]
Fair enough, didn't realise the emails weren't for PRs. But actually that's fine; for PRs we get the visual indicator at the bottom of the PR, the main reason we need emails for `master` is that we don't get that.

> So I:
> turned off builds on PRs
> turned on build on branches
> removed the "build only master branch" specification

No, I don't think that's what we want:

- builds linked to PRs are useful, you get the visual indicator of the success/failure in the PR, which is now missing from e.g. https://github.com/ably/ably-js/pull/485
- the model of 'only email on status change' doesn't make sense if it's not restricted to a single branch
- I don't really want to be emailed when someone pushes a WIP branch that's failing because it's in the middle of something, only if master fails.

For the sake of not prolonging this further, I'll merge your first commit now (but not the branch change) and reinstate PR builds in travis settings. Thanks

**Pull request merged**
