### PR TITLE
IE8 and 9 support

### PR DESCRIPTION
**Pull request by SimonWoolf**
Implementing Paddy's instructions from https://github.com/ably/wiki/issues/57.
Fixes https://github.com/ably/ably-js/issues/163.

Not perfect, but at least gets IE 8 and 9 working ok. (As long as you don't try to open more than one realtime connection in IE8 at once under certain conditions - see https://github.com/ably/ably-js/issues/211).

Note: this PR removes the XDR and iframe transports for now, per https://github.com/ably/wiki/issues/57. Will file a low-priority enhancement issue to consider re-adding them at a future time.

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Looks good to me, lots of great work here to fix so many small issues. Probably need @paddybyers' comments though before merging unfortunately

**Comment by mattheworiordan** [comment]
Given the extent of the fixes in this PR, it would be good to address the final comments @SimonWoolf in regards to using prototypes instead, and getting this merged in and published to the CDN

**Comment by SimonWoolf** [comment]
Fixup to utils as suggested: https://github.com/ably/ably-js/commit/55b18e34a4ad7a711300822cd455fc0547ce037b

Branch with the rejected polyfill commits squashed out of the history: https://github.com/ably/ably-js/compare/ie89a

**Comment by mattheworiordan** [comment]
LGTM, I think we should merge, although might need @paddybyers eye first

**Comment by paddybyers** [comment]
LGTM

**Comment by SimonWoolf** [comment]
ie89a branch merged as 3db888f

**Pull request closed without merging**
